### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by bmartus** [jthawme/stacc#12]
I was going to play around with trying to add some filters (black & white, sepia, etc.) as a feature that a similar/older gif creator application had. 

I'm having trouble getting this project up & running.  It looks like maybe some of the dependencies are relatively old?  I'm on a 2020 M1 MacBook Pro.

Do you plan to continue keeping this up to date? And would you accept any new features, if I came up with anything?

**Comment by jthawme** [comment]
Hey Brandon, unfortunately its been a long time since I've looked at this code, it would be a great idea to revive it to work on later machines, but I can remember being somewhat put off with Apple's continued pinch on apps that are not signed with a developer account signature (or something of that ilk) so it went on the back burner continuing support

**Comment by bmartus** [comment]
That makes sense .. thanks for the reply!
